### ISSUE TITLE
"measurement systems not running" in the morning

### ISSUE THREAD

**Issue by syphar** [green-coding-berlin/hog#10]
I'm testing the power-hog on my dev machine. 

Always when opening the computer in the morning (so after suspend?) I see 

<img width="373" alt="grafik" src="https://github.com/green-coding-berlin/hog/assets/540890/1df8a982-a3f7-4348-9e36-54ff5f79c109">

Currently I just re-run the setup-script again, and then it works. 

I weren't able yet to look into the setup-script, or validate the setup using the manual setup steps.

**Comment by syphar** [comment]
Is there anything you already need to debug this? 
Is there a likely broken step and something I can quickly do to fix this?

**Comment by ribalba** [comment]
Thank you for your feedback. This is something a lot of people are encountering and I still need to figure out why. Updates will be posted here.

**Comment by syphar** [comment]
Let me know when I can test something / add logging / help somehow. 

When there is a calmer morning than today I can perhaps also check what state the service is in

**Comment by syphar** [comment]
short update: I'm not sure since when, but at least since some days I didn't have to re-install in the morning any more. 

So my guess would be that one of the reinstalls gave me a new version that was fixed?

**Comment by ribalba** [comment]
I/ We have identified the issue and a fix is in the works. It was a race condition with the process we use to collect the data. Sometimes the pipe would fail and such the collection process would just wait for an empty pipe. Fix and new features incoming.

**Comment by ribalba** [comment]
Should now work with https://github.com/green-coding-berlin/hog/releases/tag/0.3

**Comment by syphar** [comment]
will test this, thanks!
