### ISSUE TITLE
Make process coalitions configurable

### ISSUE THREAD

**Issue by ribalba** [green-coding-berlin/hog#12]
On development machines it often happens that the shall turns up as head of a process coalition and such all the energy impact and cpu time is accounted to the shell process. https://github.com/green-coding-berlin/hog/issues/11

There are multiple ways this could be resolved on the client. We show this data on the server.

1) add a list of coalition names to the settings file and then resolve them. 
2) also save the subprocess of coalitions and show them in the hog app view. (This will increase the local DB size quite a bit)

**Comment by ribalba** [comment]
Closed with https://github.com/green-coding-berlin/hog/releases/tag/0.3

We will need to gather the coalition names from the server once people start modifying. 

@syphar can you please send me the coalition names so I can add them to the defaults.
I still need alacritty and kitty. I need the url like path

**Comment by syphar** [comment]
I assume the "coalition name" is the name of the process in the list in the hog? 

This would be: 
<img width="130" alt="Bildschirmfoto 2023-10-19 um 06 53 07" src="https://github.com/green-coding-berlin/hog/assets/540890/0e425880-961a-4413-a88b-0513233b0afd">

**Comment by ribalba** [comment]
perfect. Added to the defaults will roll out in version 0.4 for now you can configure it in our /etc/hog_settings.ini
```
resolve_coalitions=com.googlecode.iterm2,com.apple.Terminal,com.vix.cron,org.alacritty
```
