### ISSUE TITLE
reduce disk space usage

### ISSUE THREAD

**Issue by syphar** [green-coding-berlin/hog#22]
<img width="441" alt="grafik" src="https://github.com/green-coding-berlin/hog/assets/540890/efb4b35a-c47d-4360-9b45-80712766deda">

Having run the hog for some time, the DB size gets bigger and bigger. 

Apart from the fact that this is quite much data for not that much time (month), I feel like at the least we should have the option to delete data that is older than a certain time. Or best case, older data gets aggregated automatically, so we don't have all the details, but still have all the past statistics.

**Comment by ribalba** [comment]
Hey. Thank you for reaching out and pointing this out. I have scheduled a "compress" feature for the next release.
